spring:
  datasource:
    url: jdbc:mysql://localhost:3306/garage
    username: sa
    password: sa
    driver: com.mysql.jdbc.Driver
    outputChangeLogFile: src/main/resources/liquibase-output-change-log.xml
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
#  jackson:
#    serialization:
#      fail-on-self-references: false

